server:
  port: 8081
  servlet:
    context-path: /
    multipart:
      max-file-size: 200000000
      max-request-size: 200000000
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  tomcat:
    relaxedPathChars: '<,>,[,\,],^,`,{,|,}'
    relaxedQueryChars: '<,>,[,\,],^,`,{,|,}'
    uri-encoding: UTF-8

spring:
  datasource:
    druid:
      min-idle: 3
      max-idle: 20
      max-wait-millis: 5000  nnnnnnnnnnnnnnnnnnn
      validation-query: select 1
      initial-size: 1
      max-total: 20
      max-active: 3
      time-between-eviction-runs-millis: 60000
      test-while-idle: true
      test-on-borrow: true
      # 连接池中的minIdle数量以内的连接，空闲时间超过minEvictableIdleTimeMillis，则会执行keepAlive操作
      keepAlive: true
      # Spring 监控，利用aop 对指定接口的执行时间，jdbc数进行记录
      aop-patterns: "com.example.xnb.mapper.*"
      ########### 启用内置过滤器（第一个 stat必须，否则监控不到SQL）##########
      filters: stat,wall,log4j2
      # 自己配置监控统计拦截的filter
      filter:
        # 开启druiddatasource的状态监控
        stat:
          enabled: true
          db-type: mysql
          # 开启慢sql监控，超过2s 就认为是慢sql，记录到日志中
          log-slow-sql: true
          slow-sql-millis: 2000
        # 日志监控，使用slf4j 进行日志输出
        slf4j:
          enabled: true
          statement-log-error-enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
      ########## 配置WebStatFilter，用于采集web关联监控的数据 ##########
      web-stat-filter:
        enabled: true                   # 启动 StatFilter
        url-pattern: /*                 # 过滤所有url
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" # 排除一些不必要的url
        session-stat-enable: true       # 开启session统计功能
        session-stat-max-count: 1000    # session的最大个数,默认100
      ########## 配置StatViewServlet（监控页面），用于展示Druid的统计信息 ##########
      stat-view-servlet:
        enabled: true                   # 启用StatViewServlet
        url-pattern: /druid/*           # 访问内置监控页面的路径，内置监控页面的首页是/druid/index.html
        reset-enable: false              # 不允许清空统计数据,重新计算
        login-username: root            # 配置监控页面访问密码
        login-password: 123
        allow: 127.0.0.1
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:6789/xnb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2b8
#    username: root
#    password: a0lfkljaIhgUkhM67!8566sdf7l82a783.
    url: jdbc:mysql://103.242.12.98:6789/xnb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2b8
    username: root
    password: a0lfkljaIhgUkhM67!8566sdf7l82a783.
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  redis:
    host: 127.0.0.1
    port: 6379


file:
  image: /shiyi/image
  downloadPath: https://copisp.top/api/multiFile/download?fileName=
#  downloadPath: http://127.0.0.1:8081/multiFile/download?fileName=